// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM3q6aDH4LbnhiNtVSi4x698KFRCIzbIs',
    appId: '1:876542411964:web:2d719ba4226928e903bcb9',
    messagingSenderId: '876542411964',
    projectId: 'bank-8a513',
    authDomain: 'bank-8a513.firebaseapp.com',
    storageBucket: 'bank-8a513.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ9TfsZ5tM8743-zTYsAs1kmM7DVnkgkA',
    appId: '1:876542411964:android:60c20575ea8d902203bcb9',
    messagingSenderId: '876542411964',
    projectId: 'bank-8a513',
    storageBucket: 'bank-8a513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_qTiUPsWzBoIenu8K4nKvnA-Hqm0Uog',
    appId: '1:876542411964:ios:a6aa9943a479eb6c03bcb9',
    messagingSenderId: '876542411964',
    projectId: 'bank-8a513',
    storageBucket: 'bank-8a513.appspot.com',
    androidClientId: '876542411964-7nf9jjtt8omf9k7ebei1cfikvahl5cru.apps.googleusercontent.com',
    iosClientId: '876542411964-tn6na8aibtf3iqi3bnnj6cuouhfc7ld6.apps.googleusercontent.com',
    iosBundleId: 'com.example.watan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8_qTiUPsWzBoIenu8K4nKvnA-Hqm0Uog',
    appId: '1:876542411964:ios:b75a1bab2470082c03bcb9',
    messagingSenderId: '876542411964',
    projectId: 'bank-8a513',
    storageBucket: 'bank-8a513.appspot.com',
    androidClientId: '876542411964-7nf9jjtt8omf9k7ebei1cfikvahl5cru.apps.googleusercontent.com',
    iosClientId: '876542411964-h4cufq2vscfvpfumtesg64uoud96f9oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.watan.RunnerTests',
  );
}
